# Generated by Django 4.1.4 on 2022-12-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("date_charity", models.DateField(auto_now=True, verbose_name="Date")),
                (
                    "hours_work",
                    models.IntegerField(verbose_name="Number of Hours Worked"),
                ),
                (
                    "type_work",
                    models.CharField(
                        max_length=20, verbose_name="type of service hours worked"
                    ),
                ),
                (
                    "service_work",
                    models.CharField(
                        max_length=140, verbose_name="community serviceadmin type"
                    ),
                ),
                (
                    "describe",
                    models.CharField(
                        max_length=255, verbose_name="Description of what you did"
                    ),
                ),
            ],
        ),
    ]
