# Generated by Django 4.1.4 on 2022-12-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nwc", "0002_remove_hours_date_charity_alter_hours_describe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hours", name="hours_work", field=models.IntegerField(),
        ),
    ]
